### ISSUE TITLE
lib/kaskara/clang/backend/Dockerfile fails during build [ issue with nlohmann/json/archive/v3.1.2.tar.gz ]

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/Kaskara#59]
Using `lib/kaskara/clang/backend/Dockerfile`, the nlohmann::json v3.1.2 fails to build with these lines:
```
 && wget -nv https://github.com/nlohmann/json/archive/v3.1.2.tar.gz \
 && tar -xf v3.1.2.tar.gz \
```

Seeing the following error:
```
     raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c cd /tmp && wget -nv https://github.com/nlohmann/json/archive/v3.1.2.tar.gz  && tar -xf v3.1.2.tar.gz && cd json& && mkdir build && cd build && cmake -CMAKE_BUILD_TYPE=Debug .. && make -j4 && make install && rm -rf /tmp*' returned a non-zero code:2

```

Not sure what's the issue with `wget`, but testing Docker build without its `-nv` switch works.

@ChrisTimperley  - I checked out a couple of archive images from `nlohmann/json/archive/` and found that it takes >7m for `v3.1.2` to download, but <30s for version `v3.11.2` (this version works in the darjeeling infrastructure I'm testing).

As for solutions, I'd suggest that at a minimum, the `-nv` switch should be removed from `wget`, but I also suggest that version `v3.11.2` should be used instead.

```
 && wget https://github.com/nlohmann/json/archive/v3.11.2.tar.gz \
 && tar -xf v3.11.2.tar.gz \
```

**Comment by ChrisTimperley** [comment]
That's a strange issue. Thanks for looking into it! Feel free to make both changes 👍🏻

**Comment by pdreiter** [comment]
UPDATE: The above error was indicative of inconsistent docker build env  - after `docker image prune; docker container prune; <prepare>; <repair>` not seeing same issue.

**Comment by pdreiter** [comment]
this is good to go!
