### ISSUE TITLE
lib/kaskara/clang/backend/Dockerfile fails during build [ issue with /opt/llvm11 path ] 

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/Kaskara#60]
In docker image built by kaskara.clang.post_install:post_install:23, the resultant docker image fails to build.
Actual error:
```
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c mkdir /tmp/kaskara/build  && cd /tmp/kaskara/build  && cmake       -DCMAKE_BUILD_TYPE=Debug       -DCMAKE_PREFIX_PATH=/opt/llvm11       -DCMAKE_CXX_COMPILER=/opt/llvm11/bin/clang++       -DCMAKE_LINKER=/opt/llvm11/bin/lld       -DCMAKE_CXX_FLAGS="-I/opt/llvm11/include -g -std=c++14 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS"       ..  && make -j4' returned a non-zero code: 1
```

The docker image in `lib/kaskara/clang/backend/Dockerfile` relies on `christimperley:llvm11`, and expects `clang++` to be located at `/opt/llvm11/bin/clang++` , yet the `/opt/llvm11` directory does not exist.
However, `/opt/llvm` does exist.

@ChrisTimperley , A quick and dirty solution would be to add the following line to `lib/kaskara/clang/backend/Dockerfile`:
```RUN [ ! -e /opt/llvm11 ] && [ -e /opt/llvm ] && ln -sf /opt/llvm /opt/llvm11```
but this would probably need to be reformulated in case `/opt/llvm11` does exist

**Comment by ChrisTimperley** [comment]
Interesting. I made changes to the underlying repo for `christimperley/llvm11` to make it support multiple versions of LLVM a little more easily (e.g., `/llvm12`). I didn't consider this downstream effect 😱 

Symlinking `/opt/llvm11` to `/opt/llvm` is totally fine here.
